language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - rbx-19mode
  - jruby-19mode
matrix:
  allow_failures:
    - rvm: 2.0.0
    - rvm: rbx-19mode
    - rvm: jruby-19mode
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libxkbcommon-dev libffi-dev
  - ./install-libtsm.sh
